[project]
name = "sheets-pyspark"
version = "0.1.0"
requires-python = ">=3.11,<3.12"
dependencies = [
    "gspread",
    "pandas",
    "oauth2client",
    "ipykernel",
    "dataproc-spark-connect",
    "setuptools",
    "bigframes",
    "db-dtypes",
]
